### ISSUE TITLE
Crear BBDD Geográfica

### ISSUE THREAD

**Issue by ViajerosAdoquier** [ViajerosAdoquier/API#27]
Crear un proceso automático que descargue la base de datos geografica a partir de la API de google maps.

La estructura que tenemos que guardar será basada en el JSON que nos devuelva la API.

NOTA: crearemos una cuenta de google para obtener la key con la que conectar a la API.

**Comment by robinsound** [comment]
- Crear un `Store Locator Engine` 
- guardar resultados de búsquedas programadas
- resultados de las búsquedas de usuarios

**Comment by robinsound** [comment]
- UPDATE: hay que revisar la implicación del alcance y la duración del `cache` por la `licencia de uso`. Ver: http://stackoverflow.com/questions/4870653/maps-api-storing-data-how-to-without-violating-terms/11165215#11165215

**Comment by robinsound** [comment]
UPDATE: seguimos con GEO BBDD. ver integracion con Hotelbeds

**Comment by robinsound** [comment]
Update: `HotelBeds` no permite usar `GPS Points` (`lat` y `lng`) en el `request`. Sin embargo, cada `response` devuelve el `GPS Point` de cada `hotel`

Conclusión: hasta ahora, con los `XML Services` suministrados en la especificacion `v2013.12` no se puede buscar `availability` de `hotel` usando `lat` y `lng`

**Comment by ViajerosAdoquier** [comment]
https://developers.google.com/maps/terms#10-license-restrictions

**Comment by robinsound** [comment]
Update:
- [ ] revisar `GeoNames` para compara con `Google Maps Api `

**Comment by ViajerosAdoquier** [comment]
Finalmente usaremos google maps, para ello tendremos que crear un metodo que recoja un string y lance la busqueda contra nuestra base de datos, si no encuentra ningun resultado lanzar la peticion contra la API de googlemaps, guardar el registro y devolver los resultados.

Es posible que para gestionar el tema de las areas geograficas prefieras varias tareas, pero bueno la primera puede ser la de lanzar una peticion a googleMaps y guardar la info en base de datos (así ya tendras que comenzar con la programacion de ruby y preparar la base de datos de postgres)
